export const AI_GREETINGS = [
    "Hey! Ready to log your nasi lemak purchase?",
    "Hi! Coffee or teh tarik again today? Let’s log it 😄",
    "Hello! Your wallet survived today — let’s record the damage.",
    "Hey there! Was it mamak, kopitiam, or both?",
    "Hi! Another day, another RM quietly missing?",
    "Welcome! Let’s see where your duit pergi today.",
    "Hey! Grab, food, or parking? Tell me everything.",
    "Hello! That RM5 here RM10 there adds up — let’s log it.",
    "Hi! Ready to admit how much you spent at the mamak?",
    "Hey there! Nasi lemak is cheap… until it’s daily.",
    "Welcome! Teh ais lagi? No judgment, just tracking.",
    "Hello! Let’s catch today’s expenses before they hilang.",
    "Hey! Your bank balance would like some clarity.",
    "Hi! One expense log now, less headache end of month.",
    "Welcome! Petrol, toll, or both today?",
    "Hey there! Shopee or Lazada strike again?",
    "Hello! Let’s write down today’s spending before lupa.",
    "Hi! That ‘small amount only’ — let’s record it.",
    "Welcome! Makan luar or masak sendiri today?",
    "Hey! Parking fees quietly robbing you again?",
    "Hello! Duit keluar senyap-senyap, let’s track it.",
    "Hi! Ready to face the truth about today’s spending?",
    "Welcome! One more receipt saved from being forgotten.",
    "Hey there! Kopi mahal or kopi O today?",
    "Hello! Let’s log it before month end shock hits.",
    "Hi! Did you really need that extra side dish? 😆",
    "Welcome! Your budget called — it wants updates.",
    "Hey! Food delivery again? We’ve all been there.",
    "Hello! Let’s turn ‘agak-agak’ spending into real numbers.",
    "Hi! RM here RM there — now let’s make it clear.",
    "Welcome! Ready to adult properly for 2 minutes?",
    "Hey there! Duit keluar, data masuk.",
    "Hello! Another step towards not broke before gaji day.",
    "Hi! Let’s log expenses before blaming inflation.",
    "Welcome! Today’s spending story starts here.",
    "Hey! Was it makan, minyak, or online shopping?",
    "Hello! Your future self will thank you for this.",
    "Hi! Let’s make sense of today’s receipts.",
    "Welcome! No lecture — just logging.",
    "Hey there! Ready to keep your budget from crying?",
    "Hello! Duit keluar lagi? Let’s note it down.",
    "Hi! Tracking now beats panicking later.",
    "Welcome! End-of-month you needs this.",
    "Hey! Let’s see where your ringgit went today.",
    "Hello! Small expenses still count, you know 😄",
    "Hi! Mamak bills are sneaky — let’s log them.",
    "Welcome! Honest tracking starts now.",
    "Hey there! Your money trail ends here.",
    "Hello! Ready to log and move on with life?",
    "Hi! Let’s keep your spending in check, boss."
];

export const getRandomGreeting = (): string => {
    const index = Math.floor(Math.random() * AI_GREETINGS.length);
    return AI_GREETINGS[index];
};
